## 分发certificate
- name: Distribute kubernetes master certificate to master node
  synchronize:
    src: "/etc/kubernetes/pki/{{ item }}"
    dest: "/etc/kubernetes/pki"
    owner: yes
    group: yes
    checksum: yes # 开启校验
    perms: yes  # 保留权限
  no_log: true
  with_items:
    - admin.crt
    - admin.key
    - apiserver.crt
    - apiserver.key
    - apiserver-kubelet-client.crt
    - apiserver-kubelet-client.key
    - ca.crt
    - ca.key
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - front-proxy-client.crt
    - front-proxy-client.key
    - kube-controller-manager.crt
    - kube-scheduler.crt
    - kube-scheduler.key
    - sa.key
    - sa.pub
  when: 
  - inventory_hostname != groups['kube-master'][0]
  - inventory_hostname in groups['kube-master']
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Distribute kubelet service certificate to all nodes
  synchronize:
    src: "/var/lib/kubelet/pki/{{ item }}"
    dest: "/var/lib/kubelet/pki"
    owner: yes
    group: yes
    checksum: yes # 开启校验
    perms: yes # 开启校验
  no_log: true
  with_items:
    - kubelet.crt
    - kubelet.key
  when: 
  - inventory_hostname != groups['kube-master'][0]
  - inventory_hostname in (groups['kube-master'] + groups['kube-worker'] + groups['new-worker'])
  delegate_to: "{{ groups['kube-master'][0] }}"