- hosts: all
  roles:
    - { role: prepare/docker, when: "container_runtime == 'docker'" }
    - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
    - { role: plugins/gpu/gpu-driver, when: "container_runtime == 'docker' and has_gpu is defined and has_gpu support_gpu == 'enable'" }
    - { role: plugins/gpu/gpu-docker, when: "container_runtime == 'docker' and has_gpu is defined and has_gpu support_gpu == 'enable'" }