- hosts: new-worker
  roles:
  - { role: plugins/cluster-storage/nfs, when: "enable_nfs_provisioner == 'enable'" }
  - { role: plugins/cluster-storage/glusterfs, when: "enable_gfs_provisioner == 'enable'" }
  - { role: plugins/cluster-storage/external-ceph-block, when: "enable_external_ceph_block_provisioner == 'enable'" }
  - { role: plugins/cluster-storage/external-cephfs, when: "enable_external_cephfs_provisioner == 'enable'" }