- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - post

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - { role: plugins/dns-cache, when: "enable_dns_cache == 'enable'" }
