- hosts: kube-master[0]
  roles:
  - { role: plugins/gpu/gpu-plugin, when: "container_runtime == 'docker' and has_gpu is defined and has_gpu and support_gpu == 'enable'" }

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - post