- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - post

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - { role: plugin/dns-cache, when: "enable_dns_cache == 'enable'" }

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - { role: plugins/gpu/gpu-plugin, when: "container_runtime == 'docker' and support_gpu == 'enable'" }
