- hosts: all
  roles:
  - prepare/repository
  - prepare/base
  - prepare/nameserver
  - chrony
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
  - { role: plugins/gpu/gpu-driver, when: "container_runtime == 'docker' and has_gpu is defined and has_gpu and support_gpu == 'enable'" }
  - { role: plugins/gpu/gpu-docker, when: "container_runtime == 'docker' and has_gpu is defined and has_gpu and support_gpu == 'enable'" }
  - prepare/kubernetes
  - prepare/etcd-certificates
  - prepare/kube-certificates

- hosts: all
  roles:
  - role: load-balancer

- hosts: 
  - etcd
  - kube-master
  roles:
  - etcd

- hosts: kube-master
  roles:
  - kube-master

- hosts: 
  - kube-worker
  - new-worker
  roles:
  - kube-worker

- hosts: kube-master[0]
  roles:
  - plugins/network-plugins
  - plugins/metrics-server
  - plugins/npd
  - plugins/ingress-controller
  - { role: plugins/gpu/gpu-plugin, when: "container_runtime == 'docker' and has_gpu is defined and has_gpu and support_gpu == 'enable'" }


- hosts: kube-master
  roles:
  - helm

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - post
