- hosts: all
  roles:
  - prepare/repository
  - prepare/base
  - prepare/nameserver
  - chrony

- hosts: all
  roles:
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
  - { role: plugins/gpu/gpu-driver, when: "container_runtime == 'docker' and support_gpu == 'enable'" }
  - { role: plugins/gpu/gpu-docker, when: "container_runtime == 'docker' and support_gpu == 'enable'" }

- hosts: all
  gather_facts: false
  roles:
  - prepare/kubernetes

- hosts: all
  roles:
  - load-balancer

- hosts: localhost
  gather_facts: false
  roles:
  - prepare/certificates/etcd/generate

- hosts:
  - kube-master
  gather_facts: false
  roles:
  - prepare/certificates/etcd/distribute

- hosts: localhost
  gather_facts: false
  roles:
  - prepare/certificates/kube/generate

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - prepare/certificates/kube/distribute

- hosts:
  - etcd
  - kube-master
  gather_facts: false
  roles:
  - etcd

- hosts:
  - kube-master
  gather_facts: false
  roles:
  - kube-master

- hosts:
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - kube-worker

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/network-plugins

- hosts: kube-master
  gather_facts: false
  roles:
  - helm

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/npd

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/metrics-server

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/ingress-controller

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - post

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - { role: plugins/gpu/gpu-plugin, when: "container_runtime == 'docker' and support_gpu == 'enable'" }