- hosts: all
  roles:
  - prepare/repository
  - prepare/base
  - prepare/nameserver
  - chrony

- hosts: all
  roles:
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }

- hosts: all
  gather_facts: false
  roles:
  - prepare/kubernetes
  - prepare/etcd-certificates
  - prepare/kube-certificates

- hosts: all
  roles:
  - load-balancer

- hosts:
  - etcd
  - kube-master
  gather_facts: false
  roles:
  - etcd

- hosts:
  - kube-master
  gather_facts: false
  roles:
  - kube-master

- hosts:
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - kube-worker

- hosts: all
  gather_facts: false
  roles:
  - plugins/network-plugins/network-prepare

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/network-plugins/network-deploy

- hosts: kube-master
  gather_facts: false
  roles:
  - helm

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/metrics-server

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/ingress-controller

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - post

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - { role: plugins/dns-cache, when: "enable_dns_cache == 'enable'" }

- hosts: kube-master[0]
  gather_facts: false
  roles:
    - { role: plugins/gpu/gpu-operator, when: "container_runtime == 'docker' and support_gpu == 'enable'" }