- hosts: new-worker
  roles:
  - prepare/repository
  - prepare/base
  - chrony

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - prepare/nameserver

- hosts: new-worker
  roles:
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }

- hosts: new-worker
  gather_facts: false
  roles:
  - prepare/kubernetes

- hosts: new-worker
  roles:
  - load-balancer

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - prepare/kube-certificates

- hosts: new-worker
  gather_facts: false
  roles:
  - kube-worker

- hosts: new-worker
  gather_facts: false
  roles:
  - post

- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false
  roles:
  - plugins/network-plugins/network-prepare

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/network-plugins/network-deploy

- hosts: new-worker
  gather_facts: false
  tasks:
  - block:
    - name: Get ClusterIP of kube-dns
      shell: "{{ bin_dir }}/kubectl get svc -n kube-system | grep kube-dns | grep -v upstream | awk '{ print $3 }'"
      register: kube_dns_clusterip
      run_once: true

    - name: Modify the kubelet config file
      lineinfile:
        path: "/var/lib/kubelet/config.yaml"
        regexp: '- {{ kube_dns_clusterip.stdout }}'
        line: "- {{ pillar_local_dns }}"

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted
    when:
    - kube_proxy_mode == "ipvs"
    - enable_dns_cache == "enable"

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - { role: plugins/gpu/gpu-operator, when: "container_runtime == 'docker' and support_gpu == 'enable'" }