- hosts: new-worker
  roles:
  - prepare/repository
  - prepare/base
  - chrony
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
  - prepare/kubernetes

- hosts: new-worker
  roles:
  - load-balancer

- hosts: 
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - prepare/kube-certificates

- hosts: new-worker
  roles:
  - kube-worker

- hosts: new-worker
  roles:
  - post

- hosts: new-worker
  roles:
  - add-worker

- hosts: all
  roles:
  - plugins/network-plugins