## 分发证书
- name: Distribute etcd certificate to etcd node
  synchronize:
    src: "/etc/kubernetes/pki/etcd/{{ item }}"
    dest: "/etc/kubernetes/pki/etcd/"
    owner: yes
    group: yes
    checksum: yes # 开启校验
    perms: yes  # 保留权限
  no_log: true
  with_items:
    - ca.crt
    - ca.key
    - healthcheck-client.crt
    - healthcheck-client.key
    - peer.crt
    - peer.key
    - server.crt
    - server.key
  when:
  - inventory_hostname != groups['etcd'][0] 
  - inventory_hostname in groups['etcd']
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Distribute apiserver etcd client certificate to master node
  synchronize:
    src: "/etc/kubernetes/pki/{{ item }}"
    dest: "/etc/kubernetes/pki"
    owner: yes
    group: yes
    checksum: yes # 开启校验
    perms: yes  # 保留权限
  no_log: true
  with_items:
    - etcd/ca.crt
    - etcd/ca.key
    - apiserver-etcd-client.crt
    - apiserver-etcd-client.key
  when:
  - inventory_hostname != groups['etcd'][0] 
  - inventory_hostname in groups['kube-master']
  delegate_to: "{{ groups['etcd'][0] }}"