- name: On etcd node Create etcd directory
  file: 
    name: /etc/kubernetes/pki/etcd
    state: directory
  when: inventory_hostname in groups['etcd']

- name: On master node create etcd certificate directory
  file: 
    name: /etc/kubernetes/pki/etcd
    state: directory
  when: inventory_hostname in groups['kube-master']

- block:
  # 获取密钥状态
  - include_tasks: certs_stat.yml
  # 生成证书
  - include_tasks: generate.yml
  when: inventory_hostname == groups['etcd'][0]

# 分发证书
- include_tasks: distribute.yml