- name: NFS | install nfs-utils
  yum:
    name:
      - nfs-utils
    state: present
    update_cache: yes

- block:
    - name: NFS| set defaultvers
      replace:
        path: /etc/nfsmount.conf
        regexp: '# Defaultvers=4'
        replace: "Defaultvers=3"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['all'] }}"

    - name: set nfsvers
      replace:
        path: /etc/nfsmount.conf
        regexp: '# Nfsvers=4'
        replace: "Nfsvers=3"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['all'] }}"

    - name: NFS| set nfslock
      replace:
        path: /etc/nfsmount.conf
        regexp: '# Lock=True'
        replace: "Lock=False"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['all'] }}"
  when:
    - storage_nfs_server_version is defined and storage_nfs_server_version == "3"
  ignore_errors: true