- name: Make sure no other load balancer is running
  file: 
    name: "{{ item }}"
    state: absent
  with_items:
  - /etc/kubernetes/plugins/lb-config
  - /etc/kubernetes/manifests/lb-keepalived.yaml
  - /etc/kubernetes/manifests/lb-kube-apiserver.yaml