- name: Install haproxy
  yum:
    name:
      - haproxy
    state: present
    update_cache: yes

- name: Create haproxy directory
  file: name=/etc/haproxy state=directory

- name: Modify haproxy.service
  template:
    src: haproxy/haproxy.service.j2
    dest: /usr/lib/systemd/system/haproxy.service

- name: Configuration haproxy
  template:
    src: haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: Enable haproxy service
  service:
    name: haproxy
    enabled: yes

- name: Start haproxy service
  service:
    name: haproxy
    state: started