- name: Install haproxy
  yum:
    name:
      - haproxy
    state: present
    update_cache: yes
  when:
    - ansible_distribution in [ 'CentOS','RedHat' ]

- block:
  - name: EulerOS amd64 | Install haproxy
    yum:
      name:
        - haproxy
      state: present
      update_cache: yes
    when:
      - architectures == 'amd64'

  - name: EulerOS arm64 | Install haproxy
    dnf:
      name:
        - haproxy
      state: present
      update_cache: yes
    when:
      - architectures == 'arm64'
  when: ansible_distribution in [ 'EulerOS' ]

- name: Create haproxy directory
  file: name=/etc/haproxy state=directory

- block:
  - name: Arm64 | Modify EulerOS haproxy.service
    template:
      src: haproxy/haproxy.euler.service.j2
      dest: /usr/lib/systemd/system/haproxy.service
    when: architectures == 'arm64'

  - name: Amd64 | Modify EulerOS haproxy.service
    template:
      src: haproxy/haproxy.service.j2
      dest: /usr/lib/systemd/system/haproxy.service
    when: architectures == 'amd64'
  when: ansible_distribution in [ 'EulerOS' ]

- block:
  - name: Modify haproxy.service
    template:
      src: haproxy/haproxy.service.j2
      dest: /usr/lib/systemd/system/haproxy.service
  when: ansible_distribution in [ 'CentOS','RedHat' ]

- name: Configuration haproxy
  template:
    src: haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: Enable haproxy service
  service:
    name: haproxy
    enabled: yes

- name: Start haproxy service
  service:
    name: haproxy
    state: started