- name: Download kubeadm kubelet kubectl file
  get_url:
    validate_certs: no
    url: "{{ k8s_upgrade_download_url }}"
    dest: "{{ base_dir }}/"
    timeout: "{{ download_timeout_online }}"

- name: Unarchive kubeadm kubelet kubectl file
  unarchive:
    src: "{{ base_dir }}/k8s.tar.gz"
    dest: "{{ base_dir }}/"
    remote_src: yes

- name: Copy kubeadm kubelet kubectl file
  copy:
    src: "{{ base_dir}}/k8s/{{ item }}"
    dest: "{{ bin_dir }}/"
    remote_src: yes
    mode: "0755"
  with_items:
  - kubeadm
  - kubelet
  - kubectl

- block:
  - name: Download kube-master image
    get_url:
      validate_certs: no
      url: "{{ item }}"
      dest: "{{ base_dir }}/k8s"
      timeout: "{{ download_timeout_online }}"
    with_items:
    - "{{ kube_controller_manager_upgrade_download_url }}"
    - "{{ kube_apiserver_upgrade_download_url }}"
    - "{{ kube_scheduler_upgrade_download_url }}"

  - name: Docker | Load kube-master image
    shell: "{{ bin_dir }}/docker load -i {{ base_dir }}/k8s/{{ item }}"
    with_items:
    - kube-controller-manager.tar
    - kube-apiserver.tar
    - kube-scheduler.tar
    when: container_runtime == 'docker'

  - name: Containerd | Load kube-master image
    shell: "{{ bin_dir }}/ctr -n=k8s.io images import {{ base_dir }}/k8s/{{ item }}"
    with_items:
    - kube-controller-manager.tar
    - kube-apiserver.tar
    - kube-scheduler.tar
    when: container_runtime == 'containerd'
  when: inventory_hostname in groups['kube-master']

- block:
  - name: Download kube-proxy and pause image
    get_url:
      validate_certs: no
      url: "{{ item }}"
      dest: "{{ base_dir }}/k8s"
      timeout: "{{ download_timeout_online }}"
    with_items:
    - "{{ kube_proxy_upgrade_download_url }}"
    - "{{ pause_upgrade_download_url }}"

  - block:
    - name: Docker | Load kube-proxy image
      shell: "{{ bin_dir }}/docker load -i {{ base_dir }}/k8s/{{ item }}"
      with_items: kube-proxy.tar

    - name: Docker | Load pause image
      shell: "{{ bin_dir }}/docker load -i {{ base_dir }}/k8s/{{ item }}"
      with_items: pause.tar
    when: container_runtime == 'docker'

  - block:
    - name: Containerd | Load kube-proxy image
      shell: "{{ bin_dir }}/ctr -n=k8s.io images import {{ base_dir }}/k8s/{{ item }}"
      with_items: kube-proxy.tar

    - name: Containerd | Load pause image
      shell: "{{ bin_dir }}/ctr -n=k8s.io images import {{ base_dir }}/k8s/{{ item }}"
      with_items: pause.tar
    when: container_runtime == 'containerd'
  when: inventory_hostname in (groups['kube-worker'] + groups['new-worker'])

- include_tasks: common.yml
  when: inventory_hostname in (groups['kube-master'] + groups['kube-worker'] + groups['new-worker'])