- name: Create kubernetes directory
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ kubelet_root_dir }}"
  - /etc/kubernetes
  - /usr/share/bash-completion/completions

- name: Read kubelet.conf file stat info
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- include_tasks: "{{ (role_path + '/../kube-master/tasks/kubeadm-config.yml') | realpath  }}"
  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname not in groups['kube-master']

- block:
  - name: Confirm kubelet has stopped
    service:
      name: kubelet
      state: stopped
      enabled: yes

  - name: Worker node join the cluster
    shell: >
      kubeadm join --config /etc/kubernetes/kubeadm-config.yaml 
      --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests
  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname not in groups['kube-master']
  - not kubelet_conf_stat.stat.exists

- block:
  - name: Confirm kubelet configuration modify
    template:
      src: kubelet-config.v1beta1.yaml.j2
      dest: /var/lib/kubelet/config.yaml
      owner: root
      mode: 0644
    register: configuration_result
  
  - name: Restart kubelet service
    service:
      name: kubelet
      state: restarted
      enabled: yes
    when: configuration_result.changed
  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname not in groups['kube-master']

- name: Cancel the master node taint in the worker group
  shell: >
    kubectl taint nodes {{inventory_hostname}} node-role.kubernetes.io/master='':NoSchedule --overwrite &&
    kubectl taint nodes {{inventory_hostname}} node-role.kubernetes.io/master-
  delegate_to: "{{ groups['kube-master'][0] }}"
  ignore_errors: yes
  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname in groups['kube-master']

- name: Create kubeconfig directory
  file:
    name: "/root/.kube"
    state: directory

- name: Copy kubeconfig file to .kube directory
  copy:
    src: "{{ playbook_dir }}/{{ cluster_name }}/kubeconfig/config"
    dest: "/root/.kube/config"