- name: CentOS | Remove ntp server
  yum:
    name: ntp
    state: absent
  when: ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]
  ignore_errors: true

- name: Debian | Remove ntp server
  apt:
    name: ntp
    state: absent
  when: ansible_distribution in [ 'Ubuntu','Debian' ]
  ignore_errors: true

- name: CentOS | Install chrony
  yum:
    name: chrony
    state: present
  when: ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]

- name: Debian | Install chrony
  apt:
    name: chrony
    state: present
  when: ansible_distribution in [ 'Ubuntu','Debian' ]

- block:
  - name: Setup chrony server
    template:
      src: server-centos.conf.j2
      dest: /etc/chrony.conf

  - name:  CentOS | chrony server
    service:
      name: chronyd
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]

  - name:  Debian | start chrony server
    service:
      name: chrony
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]
  when: inventory_hostname == groups['chrony'][0]

- block:
  - name: Config chrony client
    template:
      src: client-centos.conf.j2
      dest: /etc/chrony.conf

  - name: Start chrony client
    service:
      name: chronyd
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]

  - name: Start chrony client
    service:
      name: chrony
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]

  - name: Calibration time server
    shell: "chronyc tracking"

  - name: Active sync time
    shell: "chronyc -a makestep"
    when: ansible_user == "root"
  when: 'inventory_hostname != groups.chrony[0]'