- name: Remove ntp
  shell: 'yum remove -y ntp'
  args:
    warn: false
  ignore_errors: true

- name: Install chrony
  yum:
    name:
      - chrony
    state: present
    update_cache: yes
  when:
    - ansible_distribution in [ 'CentOS','RedHat' ]

- block:
  - name: EulerOS amd64 | Install chrony
    yum:
      name:
        - chrony
      state: present
      update_cache: yes
    when:
      - architectures == 'amd64'

  - name: EulerOS arm64 | Install chrony
    dnf:
      name:
        - chrony
      state: present
      update_cache: yes
    when:
      - architectures == 'arm64'
  when: ansible_distribution in [ 'EulerOS' ]

- name: amd64 | Install chrony
  yum:
    name:
      - chrony
    state: present
    update_cache: yes

- name: arm64 | Install chrony
  dnf:
    name:
      - chrony
    state: present
    update_cache: yes
  when:
    - architectures == 'arm64'
    - ansible_distribution in [ 'EulerOS' ]

- block:
  - name: Setup chrony server
    template:
      src: server-centos.conf.j2
      dest: /etc/chrony.conf

  - name:  chrony server
    service:
      name: chronyd
      state: restarted
      enabled: yes
  when: 'inventory_hostname == groups.chrony[0]'

- block:
  - name: Config chrony client
    template:
      src: client-centos.conf.j2
      dest: /etc/chrony.conf

  - name: Start chrony client
    service:
      name: chronyd
      state: restarted
      enabled: yes

  - name: Active sync time
    shell: "chronyc -a makestep"
  when: 'inventory_hostname != groups.chrony[0]'