- name: Remove ntp
  package:
    name:
      - ntp
    state: absent
  ignore_errors: true

- name: Install chrony
  package:
    name:
      - chrony
    state: present

- block:
  - name: Setup chrony server
    template:
      src: server-centos.conf.j2
      dest: /etc/chrony.conf

  - name:  CentOS | chrony server
    service:
      name: chronyd
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'CentOS','RedHat','EulerOS' ]

  - name:  Debian | chrony server
    service:
      name: chrony
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]
  when: inventory_hostname == groups['chrony'][0]

- block:
  - name: Config chrony client
    template:
      src: client-centos.conf.j2
      dest: /etc/chrony.conf

  - name: Start chrony client
    service:
      name: chronyd
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'CentOS','RedHat','EulerOS' ]

  - name: Start chrony client
    service:
      name: chrony
      state: restarted
      enabled: yes
    when: ansible_distribution in [ 'Ubuntu','Debian' ]

  - name: Distribute ntp
    shell: "chronyc ntpdata"

  - name: Active sync time
    shell: "chronyc -a makestep"
    when: ansible_user == "root"
  when: 'inventory_hostname != groups.chrony[0]'

