- name: Create kubernetes certificates directory
  file:
    name: "{{ playbook_dir }}/{{ cluster_name }}/pki"
    state: directory

# 获取密钥状态
- include_tasks: certs_stat.yml

# 生成公共证书
- include_tasks: generate.yml