- name: Insert repository record
  lineinfile:
    path: "/etc/hosts"
    regexp: '{{ registry_hostname }}'
    line: "{{registry_hostname}} {{ dns_repository_hostname }}"

- name: Insert hosts record
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ item }}"
    line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
  with_items:
  - "{{ groups['kube-master'] }}"
  - "{{ groups['kube-worker'] }}"
  - "{{ groups['new-worker'] }}"
  when: cluster_name_style == "hostname"