- name: Confirm kubeadm version
  command: "kubeadm version -o short"
  register: kubeadm_version_output

- name: Setup kubeadm api version to v1beta1
  set_fact:
    kubeadmConfig_api_version: v1beta1
  when: 
  - kubeadm_version_output.stdout is version('v1.13.0', '>=')
  - kubeadm_version_output.stdout is version('v1.15.0', '<')

- name: Setup kubeadm api version to v1beta2
  set_fact:
    kubeadmConfig_api_version: v1beta2
  when: 
  - kubeadm_version_output.stdout is version('v1.15.0', '>=')

- name: Create kubeadm configuration file
  template:
    src: >-
      {% if inventory_hostname == groups['kube-master'][0] -%}
      kubeadm-controlplane-init.{{ kubeadmConfig_api_version }}.yaml.j2
      {%- elif inventory_hostname in groups['kube-master'] -%}
      kubeadm-controlplane-join.{{ kubeadmConfig_api_version }}.yaml.j2
      {%- else -%}
      kubeadm-join.{{ kubeadmConfig_api_version }}.yaml.j2
      {%- endif %}
    dest: "/etc/kubernetes/kubeadm-config.yaml"
    owner: root
    mode: 0644